About the author
----------------

Adrian Kosmaczewski has been writing software for the past 20 years. He started
working professionally in 1996, riding the first and second waves of the web. He
has shipped web applications using various technologies, as well as desktop
systems for Mac OS X, Windows and Linux. He is also a regular speaker at
technical conferences, and provides training and support to new developers all
over the world.

Adrian started writing Cocoa applications for the Mac in 2002, and has been
writing iOS apps since he returned from WWDC 2008. Adrian is the founder of
http://akosma.com/[akosma software], with a strong focus in all things iOS.

He has studied physics in Switzerland and economics in Buenos Aires, and holds a
Master in Information Technology with a specialization in Software Engineering
from the University of Liverpool. When not writing software, Adrian likes to
spend time with his wife Claudia. He updates his blog
http://kosmaczewski.net/["Open Kosmaczewski"] and his Twitter account
http://twitter.com/akosma[@akosma] as often as possible and is happy to have new
followers every day.

