Colophon
--------

Many of the designations used by manufacturers and sellers to
distinguish their products are claimed as trademarks. Where those
designations appear in this book, and the publisher was aware of a
trademark claim, the designations have been printed with initial capital
letters or in all capitals.

The author and publisher have taken care in the preparation of this
book, but make no expressed or implied warranty of any kind and assume
no responsibility for errors or omissions. No liability is assumed for
incidental or consequential damages in connection with or arising out of
the use of the information or programs contained herein.

Copyright © 2009-2012 akosma software. All rights reserved. Written in
Switzerland. This publication is protected by copyright, and permission
must be obtained from the publisher prior to any prohibited
reproduction, storage in a retrieval system, or transmission in any form
or by any means, electronic, mechanical, photocopying, recording, or
likewise. For information regarding permissions, or discounts for bulk
purchases and special sales, please contact Adrian Kosmaczewski (+ 41 78
739 47 76, books@akosma.com)

Visit our website at http://akosma.com/[akosma.com].

Created using Asciidoc. Kindle version generated with KindleGen by
Amazon. Text typed on Vim and  MacVim 7.3 on Mac OS X 10.7.1.

No old-fashioned printing systems were harmed during the making of this
book.

First edition, January 2012.

