'\" t
.\"     Title: The Quest Of Life: A journey through sea and land
.\"    Author: Adrian Kosmaczewski
.\" Generator: Asciidoctor 1.5.6.1
.\"      Date: 2017-08-22
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "THE QUEST OF LIFE: A JOURNEY THROUGH SEA AND LAND" "1" "2017-08-22" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.LINKSTYLE blue R < >
.SH "COLOPHON"
.sp
The Asciidoctor Press, Ceres and Denver
.sp
\(co 2013 by The Asciidoctor Press
.sp
Published in the Milky Way Galaxy
.sp
This book is designed by Dagger Flush, Denver, Colorado.
The types are handset Chinchilla and Dust, designed by Leeloo.
Leeloo designed the typefaces to soften the bluntness of documentation.
Created in Asciidoctor and Fedora 19.
The printing and binding is by Ceres Lithographing, Inc., Ceres, Milky Way.
.SH "DEDICATION"
.sp
For S.S.T.\-\-
.sp
thank you for the plague of archetypes.
.SH "PREFACE"
.sp
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
.SH "THE ATTACK OF THE CLONES"
.sp
This is the introduction to the first part of our mud\-encrusted journey.
.sp
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
.sp
.B UIViewController States
.br
.sp
.if n \{\
.RS 4
.\}
.nf
title UIViewController States

legend right
    We use states to make the code easier to understand
endlegend

[*] \-\-> Idle
Idle \-\-> [*]
Idle : Right after starting

Idle \-> Done
Done : Right before stopping
Done \-\-> [*]
.fi
.if n \{\
.RE
.\}
.SH "THE BOOK OF THE THRILLS"
.sp
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Artist
T}:T{
.sp
Track
T}:T{
.sp
Genre
T}
T{
.sp
Baauer
T}:T{
.sp
Harlem Shake
T}:T{
.sp
Hip Hop
T}
T{
.sp
The Lumineers
T}:T{
.sp
Ho Hey
T}:T{
.sp
Folk Rock
T}
.TE
.sp
.sp
Lorem ipsum dolor sit amet, consectetur
adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa
qui officia deserunt mollit anim id est laborum.
.sp
.B UIResponder Hierarchy Diagram
.br
.sp
.if n \{\
.RS 4
.\}
.nf
title UIResponder Hierarchy Diagram

legend right
  <b>UIViewController</b> and <b>UIView</b>
  are subclasses of UIResponder
endlegend

note right of NSObject : In Swift, every class\(rsnextends this one.

class NSObject << (P,LightGray) >>
class UIResponder
class UIView
class UIViewController

NSObject <|\-\- UIResponder
UIResponder <|\-\- UIView
UIResponder <|\-\- UIViewController
.fi
.if n \{\
.RE
.\}
.SS "Conclusion"
.sp
Chapter one is over. But before we leave, a checklist of stuff not to forget:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
buy milk
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
buy bread
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
call mum
.RE
.SH "MORE ABOUT JANE"
.sp
Chapter two has just begun.
.sp
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
.SS "Mathematics"
.sp
This are very important equations; make sure you learn them by heart.
\[k_{n+1} = n^2 + k_n^2 - k_{n-1}\]
\[\cos (2\theta) = \cos^2 \theta - \sin^2 \theta\]
\[f(n) = n^5 + 4n^2 + 2 |_{n=17}\]
\[\frac{n!}{k!(n-k)!} = \binom{n}{k}\]
\[  x = a_0 + \cfrac{1}{a_1
          + \cfrac{1}{a_2
          + \cfrac{1}{a_3 + \cfrac{1}{a_4} } } }\]
\[M = \begin{bmatrix}
       \frac{5}{6} &amp; \frac{1}{6} &amp; 0           \\[0.3em]
       \frac{5}{6} &amp; 0           &amp; \frac{1}{6} \\[0.3em]
       0           &amp; \frac{5}{6} &amp; \frac{1}{6}
     \end{bmatrix}\]
\[\left(\!
    \begin{array}{c}
      n \\
      r
    \end{array}
  \!\right) = \frac{n!}{r!(n-r)!}\]
.sp
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
.sp
\fIThe Pragmatic Programmer\fP [prag] should be required reading for all
developers.

.SS "Some code samples"
.sp
This is section 1 of chapter 2. We are going to add more JavaScript code, but
before, some Swift.
.sp
.if n \{\
.RS 4
.\}
.nf
 func test() \-> String { \fB(1)\fP
         return "Yeah"
 }
.fi
.if n \{\
.RE
.\}
.TS
tab(:);
r lw(\n(.lu*75u/100u).
\fB(1)\fP\h'-2n':T{
This is very important!
T}
.TE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
.B Note
.ps -1
.br
.sp
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
sunt in culpa qui officia deserunt mollit anim id est laborum.
.sp .5v
.RE
.sp
More code:
.sp
.if n \{\
.RS 4
.\}
.nf
 function test() {
     var boom = "boom";
     alert(boom);
 }
.fi
.if n \{\
.RE
.\}
.SH "EPIGRAPH"
.sp
Thanks for reading!
.SH "COPYRIGHT AND LICENSE"
.sp
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
.SH "SHORTCUTS"
.TS
allbox tab(:);
lt lt.
T{
.sp
Shortcut
T}:T{
.sp
Purpose
T}
T{
.sp
F11
T}:T{
.sp
Toggle fullscreen
T}
T{
.sp
Ctrl\0+\0T
T}:T{
.sp
Open a new tab
T}
T{
.sp
Cmd\0+\0Option\0+\0N
T}:T{
.sp
New incognito window
T}
T{
.sp
Cmd\0+\0+
T}:T{
.sp
Increase zoom
T}
.TE
.sp
.SH "GLOSSARY"
.sp
mud
.RS 4
wet, cold dirt
.RE
.sp
rain
.RS 4
water falling from the sky
.RE
.SH "QUESTIONS AND ANSWERS"
.sp
1. What is Asciidoctor?
.RS 4
An implementation of the AsciiDoc processor in Ruby.
.RE
.sp
2. What is the answer to the Ultimate Question?
.RS 4
42
.RE
</Users/akosma/Dropbox/Current/eBook-Template/images/rPQoq7ThGAU> (video)
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.B Table 1. Applications
.TS
allbox tab(:);
lt lt lt.
T{
.sp
Name
T}:T{
.sp
Category
T}:T{
.sp
Description
T}
T{
.sp
Firefox
T}:T{
.sp
Browser
T}:T{
.sp
Mozilla Firefox is an open\-source web browser.
It\(cqs designed for standards compliance,
performance, portability.
T}
T{
.sp
Arquillian
T}:T{
.sp
Testing
T}:T{
.sp
An innovative and highly extensible testing platform.
Empowers developers to easily create real, automated tests.
T}
.TE
.sp
.SH "BIBLIOGRAPHY"
.sp
.B Books
.br
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
 David Flanagan.
\c
.URL "http://oreilly.com/catalog/9780596805531" "JavaScript: The Definitive Guide,
Sixth Edition" . O\(cqReilly. 2011. ISBN 0\-596\-80552\-7
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
 Douglas Crockford.
.URL "http://oreilly.com/catalog/9780596517748" "JavaScript: The Good Parts" "."
O\(cqReilly. 2008. ISBN 0\-596\-51774\-2.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
 Stoyan Stefanov.
.URL "http://shop.oreilly.com/product/9780596806767.do" "JavaScript Patterns" "."
O\(cqReilly. 2010. ISBN 0\-596\-80675\-2.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
 Jeremy Keith.
\c
.URL "http://www.abookapart.com/products/html5\-for\-web\-designers" "HTML5 for Web
Designers" . A Book Apart. 2010. ISBN 978\-0\-9844425\-0\-8.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
 Dan Cederholm
\c
.URL "http://www.abookapart.com/products/css3\-for\-web\-designers" "CSS3 for Web
Designers" . A Book Apart. 2011. ISBN 978\-0\-9844425\-2\-2.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
 Andy Hunt &amp; Dave Thomas. The Pragmatic Programmer: From Journeyman
to Master. Addison\-Wesley. 1999.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
 Dan Allen. Seam in Action. Manning Publications.  2008.
.RE
.sp
.B Websites
.br
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.URL "http://nodejs.org/" "Official Node.js Website" ""
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.URL "http://nodejs.org/docs/latest/api/index.html" "Latest Node.js documentation" ""
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.URL "http://nodeguide.com/style.html" "Node.js Style Guide" ""
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
.URL "http://www.nodebeginner.org/" "Node.js Tutorial" ""
.RE
.SH "AUTHOR(S)"
.sp
\fBAdrian Kosmaczewski\fP
.RS 4
Author(s).
.RE